#!/bin/bash

echo """
CLIENT_ID=$PRODUCTION_EDGE_WEBSTORE_CLIENT_ID
CLIENT_SECRET=$PRODUCTION_EDGE_WEBSTORE_CLIENT_SECRET
ACCESS_TOKEN_URL=$PRODUCTION_EDGE_WEBSTORE_ACCESS_TOKEN_URL
ACCESS_TOKEN=$PRODUCTION_EDGE_WEBSTORE_ACCESS_TOKEN
PRODUCT_ID=$PRODUCTION_EDGE_WEBSTORE_PRODUCT_ID
ZIP=packages/extension.edge.{version}.zip
""" > edge.env

echo """
REFRESH_TOKEN=$PRODUCTION_CHROME_WEBSTORE_REFRESH_TOKEN
CLIENT_ID=$PRODUCTION_CHROME_WEBSTORE_CLIENT_ID
CLIENT_SECRET=$PRODUCTION_CHROME_WEBSTORE_CLIENT_SECRET
EXT_ID=$PRODUCTION_CHROME_WEBSTORE_EXTENSION_ID
ZIP=packages/extension.chrome.{version}.zip
""" > chrome.env


# echo """
# sessionid=$PRODUCTION_FIREFOX_WEBSTORE_SESSION_ID
# EXT_ID=boundless-digital-for-meraki
# ZIP="packages/extension.firefox.{version}.zip"
# """ > firefox.env